<a href="https://colab.research.google.com/github/visiont3lab/deep-learning-course/blob/main/colab/NeuralNetPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Neural net pytorch

## Feedforward steps

In [ ]:
import torch

device = torch.device('cpu')
if (torch.cuda.is_available()):
  print("Is gpu available: ", torch.cuda.is_available())
  device = torch.device('cuda:0')

X = torch.tensor([
                  [1,2],
                  [3,4],
                  [4,6],
                  [1,3],
                  [1,2],
                  [3,4],
                  [4,6],
                  [1,3],
                ], dtype=torch.float32,device=device).T

Y = torch.tensor([
                  [2],
                  [4],
                  [6],
                  [3],
                  [2],
                  [4],
                  [6],
                  [3],
                ], dtype=torch.float32,device=device)

WI = torch.tensor([ 
                  [3,2], # 1
                  [2,1], # 2
                  [2,3], # 3
                ],dtype=torch.float32, device=device)

BI = torch.tensor([[1,2,3]],dtype=torch.float32, device=device).T

WO = torch.tensor([ 
                  [2, 3, 2], # 1
                ],dtype=torch.float32,device=device)

BO = torch.tensor([[2]],dtype=torch.float32,device=device).T

# Load to gpu
#X = X.to(device)
#WI = WI.to(device)
#BI = BI.to(device)
#WO = WO.to(device)
#BO = BO.to(device)

print(WI.shape,X.shape, BI.shape)
V = torch.sigmoid( torch.matmul(WI, X) + BI )
Y_hat = (torch.matmul(WO, V) + BO ).T
print(Y_hat)
print(Y)

# Training metric (Cost function)
mse = torch.sum( torch.pow(Y_hat - Y,2) ) / Y.shape[0]
#mae = torch.sum( torch.abs(Y_hat - Y ) ) / Y.shape[0] 

# Metric validation (metrica per capire quando un modello è meglio di un altro)
print(mse)
#print(mae)
# Backprogation ()


torch.Size([3, 2]) torch.Size([2, 8]) torch.Size([3, 1])
tensor([[8.9919],
        [9.0000],
        [9.0000],
        [8.9972],
        [8.9919],
        [9.0000],
        [9.0000],
        [8.9972]])
tensor([[2.],
        [4.],
        [6.],
        [3.],
        [2.],
        [4.],
        [6.],
        [3.]])
tensor(29.7131)


## Using Pytorch Net class

In [ ]:
import torch
#!pip install torch

device = torch.device('cpu')
if (torch.cuda.is_available()):
  device = torch.device('cuda:0')
  print(device, torch.cuda.get_device_name(0))

class Manuel(torch.nn.Module):
  def __init__(self):
    super(Manuel, self).__init__()
    # Init the element
    self.h1 = torch.nn.Linear(1,5)
    self.h2 = torch.nn.Linear(5,3)
    self.o = torch.nn.Linear(3,1)
  def forward(self, x):
    # Feedforward
    x = torch.sigmoid( self.h1(x) )# x*W +b
    x = torch.sigmoid( self.h2(x) )# x*W +b
    y = self.o(x) # x*W +b
    return y

# Setup
net = Manuel().to(device)
x = torch.tensor([[2],[3],[4]], dtype=torch.float32, device=device)

# Prediction
y_hat = net(x)
print(y_hat)
#print(y_hat.detach())

# Produzione
with torch.no_grad():
  y_hat = net(x)
  print(y_hat.cpu().numpy())

In [ ]:
import torch

device = torch.device('cpu')
if (torch.cuda.is_available()):
  print("Is gpu available: ", torch.cuda.is_available())
  device = torch.device('cuda:0')
  print(torch.cuda.get_device_name(0))

class MyNet(torch.nn.Module):
  def __init__(self):
    super(MyNet, self).__init__()
    # Hidden layer
    self.H = torch.nn.Linear(2,3)
    self.H.weight = torch.nn.Parameter( torch.tensor([[3,2], [2,1],[2,3]], dtype=torch.float32))
    self.H.bias = torch.nn.Parameter(torch.tensor([[1,2,3]],dtype=torch.float32))
    
    # Output layer
    self.O = torch.nn.Linear(3,1)
    self.O.weight = torch.nn.Parameter(torch.tensor([[2, 3, 2]], dtype=torch.float32))
    self.O.bias = torch.nn.Parameter(torch.tensor([[2]],dtype=torch.float32))
    
  def forward(self,x):
    v = torch.sigmoid( self.H(x) )
    y = self.O(v)
    return y


# Input Shape: number of samples x number of input  Nx2
# Output Shape: number of samples x number of output Nx1

X = torch.tensor([
                  [1,2],
                  [3,4],
                  [4,6],
                  [1,3],
                  [1,2],
                  [3,4],
                  [4,6],
                  [1,3],
                ], dtype=torch.float32,device=device)

Y = torch.tensor([
                  [2],
                  [4],
                  [6],
                  [3],
                  [2],
                  [4],
                  [6],
                  [3],
                ], dtype=torch.float32,device=device)

# Create Net
model = MyNet()
model = model.to(device)
Y = model(X)
print(Y)

# Print weights
#for name, param in model.named_parameters():
#  print(name,param)

#print( model.H.weight, model.H.bias )
#print( model.O.weight, model.O.bias )

tensor([[8.9919],
        [9.0000],
        [9.0000],
        [8.9972],
        [8.9919],
        [9.0000],
        [9.0000],
        [8.9972]], grad_fn=<AddmmBackward0>)
